#version 430
layout(local_size_x = 1, local_size_y = 1) in;
layout(rgba32f, binding = 0) uniform image2D img_output;
uniform float time;

void main() {
  ivec2 storePos = ivec2(gl_GlobalInvocationID.xy);\
  float localCoef = length(vec2(ivec2(gl_LocalInvocationID.xy)-8)/8.0);\
  float globalCoef = sin(float(gl_WorkGroupID.x+gl_WorkGroupID.y)*0.1 + time*10)*0.5;\
  imageStore(img_output, storePos, vec4(vec3(0.8-globalCoef*localCoef), 0.0));\
}